//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfaceTouchCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurfaceTouchCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\devcon\8.0\x64\.
        /// </summary>
        internal static string devcon_8_0_64 {
            get {
                return ResourceManager.GetString("devcon_8_0_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\devcon\8.0\x86\.
        /// </summary>
        internal static string devcon_8_0_86 {
            get {
                return ResourceManager.GetString("devcon_8_0_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\devcon\8.1\x64\.
        /// </summary>
        internal static string devcon_8_1_64 {
            get {
                return ResourceManager.GetString("devcon_8_1_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\devcon\8.1\x86\.
        /// </summary>
        internal static string devcon_8_1_86 {
            get {
                return ResourceManager.GetString("devcon_8_1_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable &quot;{0}&quot;.
        /// </summary>
        internal static string devcon_disable {
            get {
                return ResourceManager.GetString("devcon_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable &quot;{0}&quot;.
        /// </summary>
        internal static string devcon_enable {
            get {
                return ResourceManager.GetString("devcon_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devcon.exe.
        /// </summary>
        internal static string devcon_exe {
            get {
                return ResourceManager.GetString("devcon_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status &quot;{0}&quot;.
        /// </summary>
        internal static string devcon_status {
            get {
                return ResourceManager.GetString("devcon_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .*disabled.*.
        /// </summary>
        internal static string regex_disabled {
            get {
                return ResourceManager.GetString("regex_disabled", resourceCulture);
            }
        }
    }
}
